# https://cloud.google.com/cloud-build/docs/configuring-builds/build-test-deploy-artifacts#deploying_artifacts
FROM node:8.16.1
RUN npm install -g firebase-tools@7.3.0
ENTRYPOINT ["/usr/local/bin/firebase"]
